version: '3.8'

services:
  php:
    build: .
    ports:
      - "8020:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: santrify_db
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3386:3306"
    volumes:
      - db_data_santrify:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data_santrify:

networks:
  app-network:
